import { StyleSheet } from "react-native";

import {
  brut,
  colors,
  drop,
  fonts,
  radii,
  spacing,
  typography,
} from "../../../shared/theme/tokens";

export const styles = StyleSheet.create({
  uploadCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: brut.border,
    borderRadius: radii.xl,
    padding: spacing.xl,
    gap: spacing.lg,
    boxShadow: drop(4),
    marginBottom: spacing.xxl2,
  },
  uploadIntro: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  uploadIcon: {
    width: 48,
    height: 48,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceTint,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadCopy: { flex: 1, gap: spacing.xs },
  uploadTitle: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: typography.h3.fontSize,
    lineHeight: typography.h3.lineHeight,
  },
  uploadDescription: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.sub.fontSize,
    lineHeight: typography.sub.lineHeight,
  },
  uploadLimit: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption.fontSize,
    lineHeight: typography.caption.lineHeight,
    textAlign: "center",
  },
  photoHeading: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: spacing.md,
  },
  photoHeadingText: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: typography.h3.fontSize,
  },
  photoCount: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.caption.fontSize,
  },
  emptyText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.sub.fontSize,
    marginBottom: spacing.lg,
  },
  selectedMedia: { borderWidth: 3, borderColor: colors.primaryAccessible },
  mediaImage: { width: "100%", height: "100%" },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  slot: {
    aspectRatio: 0.78,
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceSunken,
    borderWidth: brut.border,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  slotEmpty: {
    backgroundColor: colors.surfaceSunken,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: colors.border,
  },
  add: {
    alignItems: "center",
    gap: spacing.xs,
  },
  remove: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 22,
    height: 22,
    borderRadius: radii.pill,
    backgroundColor: colors.overlayScrim,
    alignItems: "center",
    justifyContent: "center",
  },
  mainBadge: {
    position: "absolute",
    left: spacing.sm,
    bottom: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  mainBadgeText: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: typography.micro.fontSize,
  },
  photoHint: {
    marginTop: spacing.lg,
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.sub.fontSize,
  },
});
