/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccountStatusEnum = "ACTIVE" | "DELETED" | "SUSPENDED";

export type CircleStatusEnum = "active" | "retired";

export type ConversationTypeEnum = "circle" | "direct";

export type CycleStatusEnum = "active" | "closed" | "forming";

export type DatingGoalEnum = "CASUAL_DATING" | "FRIENDSHIP" | "LONG_TERM_RELATIONSHIP" | "UNSURE";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type MessageTypeEnum = "media" | "system" | "text";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRoleEnum = "STAFF" | "USER";

export type VerificationStatusEnum = "APPROVED" | "EXPIRED" | "IN_REVIEW" | "PENDING" | "REJECTED";

export type VerificationTypeEnum = "DRIVERS_LICENSE" | "NATIONAL_ID" | "PASSPORT" | "PROOF_OF_AGE_CARD" | "RESIDENCE_PERMIT";

export interface CircleCycles {
  circleId: number;
  createdAt: Generated<Timestamp>;
  cycleId: Generated<number>;
  endsAt: Timestamp;
  startsAt: Timestamp;
  status: Generated<CycleStatusEnum>;
}

export interface CircleMembers {
  cycleId: number;
  joinedAt: Generated<Timestamp>;
  leftAt: Timestamp | null;
  userId: number;
}

export interface Circles {
  circleId: Generated<number>;
  createdAt: Generated<Timestamp>;
  name: string;
  status: Generated<CircleStatusEnum>;
  updatedAt: Generated<Timestamp>;
}

export interface ConversationMembers {
  conversationId: number;
  joinedAt: Generated<Timestamp>;
  lastReadMessageId: Int8 | null;
  leftAt: Timestamp | null;
  userId: number;
}

export interface Conversations {
  conversationId: Generated<number>;
  createdAt: Generated<Timestamp>;
  cycleId: number | null;
  dmKey: string | null;
  lastMessageAt: Timestamp | null;
  type: ConversationTypeEnum;
  updatedAt: Generated<Timestamp>;
}

export interface Genders {
  genderId: Generated<number>;
  genderName: string;
  updatedAt: Generated<Timestamp>;
}

export interface IdVerifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  provider: string;
  providerReference: string | null;
  status: Generated<VerificationStatusEnum>;
  updatedAt: Generated<Timestamp>;
  userId: number;
  verificationId: Generated<number>;
  verificationType: VerificationTypeEnum | null;
  verifiedAt: Timestamp | null;
}

export interface Interests {
  createdAt: Generated<Timestamp>;
  interestId: Generated<number>;
  interestName: string;
  isActive: boolean;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface LifestyleOptions {
  createdAt: Generated<Timestamp>;
  displayOrder: number;
  isActive: Generated<boolean>;
  label: string;
  lifestyleOptionId: Generated<number>;
  lifestyleQuestionId: number;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface LifestyleQuestions {
  createdAt: Generated<Timestamp>;
  displayOrder: number;
  isActive: Generated<boolean>;
  lifestyleQuestionId: Generated<number>;
  questionText: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface Medias {
  createdAt: Generated<Timestamp>;
  fileSizeBytes: Int8;
  mediaId: Generated<number>;
  mediaUrl: string;
  mimeType: string;
}

export interface Messages {
  body: string | null;
  conversationId: number;
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  messageId: Generated<Int8>;
  messageType: Generated<MessageTypeEnum>;
  userId: number | null;
}

export interface ProfileInterests {
  createdAt: Generated<Timestamp>;
  interestId: number;
  userId: number;
}

export interface ProfileLifestyleAnswers {
  createdAt: Generated<Timestamp>;
  lifestyleOptionId: number;
  lifestyleQuestionId: number;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface ProfilePhotos {
  isPrimary: boolean;
  mediaId: Generated<number>;
  photoOrder: number;
  updatedAt: Timestamp;
  userId: Generated<number>;
}

export interface ProfilePrompts {
  answer: string;
  createdAt: Generated<Timestamp>;
  displayOrder: number;
  promptId: number;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Profiles {
  bio: string | null;
  createdAt: Generated<Timestamp>;
  dateOfBirth: Timestamp;
  datingGoal: DatingGoalEnum | null;
  displayName: string;
  genderId: number | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Prompts {
  createdAt: Generated<Timestamp>;
  isActive: Generated<boolean>;
  promptId: Generated<number>;
  promptText: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface SchemaMigrations {
  version: string;
}

export interface UserPreferences {
  createdAt: Generated<Timestamp>;
  maxAge: number;
  maxDistanceKm: number;
  minAge: number;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Users {
  accountStatus: Generated<AccountStatusEnum>;
  authProviderUserId: string;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  userId: Generated<number>;
  userRole: Generated<UserRoleEnum>;
}

export interface UsersLocation {
  city: string | null;
  country: string | null;
  latitude: Numeric;
  locationUpdatedAt: Generated<Timestamp>;
  longitude: Numeric;
  postcode: string | null;
  state: string | null;
  userId: number;
}

export interface VerificationEvents {
  eventId: string;
  processedAt: Generated<Timestamp>;
}

export interface DB {
  circleCycles: CircleCycles;
  circleMembers: CircleMembers;
  circles: Circles;
  conversationMembers: ConversationMembers;
  conversations: Conversations;
  genders: Genders;
  idVerifications: IdVerifications;
  interests: Interests;
  lifestyleOptions: LifestyleOptions;
  lifestyleQuestions: LifestyleQuestions;
  medias: Medias;
  messages: Messages;
  profileInterests: ProfileInterests;
  profileLifestyleAnswers: ProfileLifestyleAnswers;
  profilePhotos: ProfilePhotos;
  profilePrompts: ProfilePrompts;
  profiles: Profiles;
  prompts: Prompts;
  schemaMigrations: SchemaMigrations;
  userPreferences: UserPreferences;
  users: Users;
  usersLocation: UsersLocation;
  verificationEvents: VerificationEvents;
}
